<?php

use App\Dependence;
use Illuminate\Database\Seeder;

class DependencesTableSeeder extends Seeder
{
    public function run()
    {
        Dependence::create(["code"=>'0001', "dependence"=>'OTROS BIENES MUEBLES', "ubication"=>'']);
		Dependence::create(["code"=>'0002', "dependence"=>'CONTRALORIA INTERNA', "ubication"=>'']);
		Dependence::create(["code"=>'0003', "dependence"=>'CUBICULO DE PROFESORES (ZARAZA)', "ubication"=>'']);
		Dependence::create(["code"=>'0004', "dependence"=>'SALA DE REPRODUCCION (ZARAZA)', "ubication"=>'']);
		Dependence::create(["code"=>'0005', "dependence"=>'CENTRO DE ESTUDIANTES (ZARAZA)', "ubication"=>'']);
		Dependence::create(["code"=>'0006', "dependence"=>'COMEDOR ESTUDIANTIL (ZARAZA)', "ubication"=>'']);
		Dependence::create(["code"=>'0007', "dependence"=>'OFICINA DE CULTURA (ZARAZA)', "ubication"=>'']);
		Dependence::create(["code"=>'0008', "dependence"=>'MANTENIMIENTO (ZARAZA)', "ubication"=>'']);
		Dependence::create(["code"=>'0009', "dependence"=>'COORDINACION DE EXTENSION (ZARAZA)', "ubication"=>'']);
		Dependence::create(["code"=>'0010', "dependence"=>'DIRECCION DE PROGRAMAS ACADEMICOS (ZARAZA)', "ubication"=>'']);
		Dependence::create(["code"=>'0011', "dependence"=>'DIRECCION DE PROGRAMA DE ENFERMERIA', "ubication"=>'']);
		Dependence::create(["code"=>'0012', "dependence"=>'COORDINACION DE PROFESIONALIZACION', "ubication"=>'']);
		Dependence::create(["code"=>'0013', "dependence"=>'LABORATORIO AREA DE SALUD', "ubication"=>'']);
		Dependence::create(["code"=>'0014', "dependence"=>'CUBICULO DE PROFESORES DEPT. DE CLINICAS AREA SALUD', "ubication"=>'']);
		Dependence::create(["code"=>'0015', "dependence"=>'AULAS UNERG  AREA DE ENFERMERIA', "ubication"=>'']);
		Dependence::create(["code"=>'0016', "dependence"=>'RESTAURANT RECTORADO', "ubication"=>'']);
		Dependence::create(["code"=>'0017', "dependence"=>'CELLUNERG', "ubication"=>'']);
		Dependence::create(["code"=>'0018', "dependence"=>'FUNDERG', "ubication"=>'']);
		Dependence::create(["code"=>'0019', "dependence"=>'DEPARTAMENTO DE AUDIOVISUALES AGRONOMIA', "ubication"=>'']);
		Dependence::create(["code"=>'0020', "dependence"=>'DIRECCION DE PROTOCOLO', "ubication"=>'']);
		Dependence::create(["code"=>'0101', "dependence"=>'CONSEJO UNIVERSITARIO', "ubication"=>'']);
		Dependence::create(["code"=>'0102', "dependence"=>'SECRETARIA', "ubication"=>'']);
		Dependence::create(["code"=>'0103', "dependence"=>'CENTRO DE ESTUDIANTES CS ECONOMICAS', "ubication"=>'']);
		Dependence::create(["code"=>'0104', "dependence"=>'LABORATORIO DE INVESTIGACION ', "ubication"=>'']);
		Dependence::create(["code"=>'0105', "dependence"=>'HOSPITAL DE GRANDES ANIMALES (ZARAZA)', "ubication"=>'']);
		Dependence::create(["code"=>'0106', "dependence"=>'CENTRO DE ESTUDIOS E INVESTIGACION DE CS SALUD', "ubication"=>'']);
		Dependence::create(["code"=>'0107', "dependence"=>'SITRAUNERG', "ubication"=>'']);
		Dependence::create(["code"=>'0108', "dependence"=>'CENTRO DE INVESTIGACION DE LA MUJER', "ubication"=>'']);
		Dependence::create(["code"=>'0109', "dependence"=>'CENTRO DE ESTUDIOS AMBIENTALES Y AGROECOLOGICOS', "ubication"=>'']);
		Dependence::create(["code"=>'0110', "dependence"=>'CIENCIAS POLITICAS Y JURIDICAS', "ubication"=>'']);
		Dependence::create(["code"=>'0111', "dependence"=>'COOPERATIVA PIONERA DE GUARICO CASONA', "ubication"=>'']);
		Dependence::create(["code"=>'0112', "dependence"=>'ESCUELA BOLIVARIANA DE VCECINOS CASONA', "ubication"=>'']);
		Dependence::create(["code"=>'0113', "dependence"=>'COORDINACION ACADEMICA AREA CS DE LA SALUD', "ubication"=>'']);
		Dependence::create(["code"=>'0114', "dependence"=>'CENTRO DE PRODUCCION CUNICOLA', "ubication"=>'']);
		Dependence::create(["code"=>'0115', "dependence"=>'CENTRO ENDOGENO DE LACTEOS', "ubication"=>'']);
		Dependence::create(["code"=>'0116', "dependence"=>'DEFENSORIA ESTUDIANTIL', "ubication"=>'']);
		Dependence::create(["code"=>'0117', "dependence"=>'FUNDACITE', "ubication"=>'']);
		Dependence::create(["code"=>'0118', "dependence"=>'SALA SITUACIONAL RENTAL', "ubication"=>'']);
		Dependence::create(["code"=>'0119', "dependence"=>'FUNDEMURG - RADIO', "ubication"=>'']);
		Dependence::create(["code"=>'0120', "dependence"=>'SALA SITUACIONAL DE GOBIERNO Y POLITICAS PUBLICAS', "ubication"=>'']);
		Dependence::create(["code"=>'0201', "dependence"=>'OFICINA DE RECTOR', "ubication"=>'']);
		Dependence::create(["code"=>'0202', "dependence"=>'DIRECCION DE PRENSA', "ubication"=>'']);
		Dependence::create(["code"=>'0203', "dependence"=>'DECANATO DE INVESTIGACION Y EXTENSION', "ubication"=>'']);
		Dependence::create(["code"=>'0204', "dependence"=>'SECRETARIA DEL RECTOR', "ubication"=>'']);
		Dependence::create(["code"=>'0205', "dependence"=>'OFICINA SECTORIAL DE ADM.CONTROL Y EVAL. DE ESTUDIOS', "ubication"=>'']);
		Dependence::create(["code"=>'0206', "dependence"=>'CENTRO DE ESTUDIANTES AREA ODONTOLOGIA', "ubication"=>'']);
		Dependence::create(["code"=>'0207', "dependence"=>'MULTIHOGAR UNERG', "ubication"=>'']);
		Dependence::create(["code"=>'0208', "dependence"=>'DIRECCION DE SUPERVISION ACADEMICA', "ubication"=>'']);
		Dependence::create(["code"=>'0209', "dependence"=>'CUERPO DE BOMBEROS UNIVERSITARIOS', "ubication"=>'']);
		Dependence::create(["code"=>'0210', "dependence"=>'DECANATO DE ODONTOLOGIA', "ubication"=>'']);
		Dependence::create(["code"=>'0211', "dependence"=>'CONSULTORIO MEDICO UNERG', "ubication"=>'']);
		Dependence::create(["code"=>'0212', "dependence"=>'DECANATO DE POST GRADO', "ubication"=>'']);
		Dependence::create(["code"=>'0213', "dependence"=>'ASESORIA JURIDICA', "ubication"=>'']);
		Dependence::create(["code"=>'0214', "dependence"=>'DIRECCION DE PLANIFICACION', "ubication"=>'']);
		Dependence::create(["code"=>'0215', "dependence"=>'SALA DE REPRODUCCION ACADEMICA', "ubication"=>'']);
		Dependence::create(["code"=>'0216', "dependence"=>'CONSEJO DE APELACIONES', "ubication"=>'']);
		Dependence::create(["code"=>'0217', "dependence"=>'DIRECCION DE PLANTA FISICA', "ubication"=>'']);
		Dependence::create(["code"=>'0218', "dependence"=>'CENTRO DE ESTUDIANTES DE ENFERMERIA', "ubication"=>'']);
		Dependence::create(["code"=>'0219', "dependence"=>'DIRECCION DE CULTURA', "ubication"=>'']);
		Dependence::create(["code"=>'0220', "dependence"=>'DEPARTAMENTO DE NOMINA', "ubication"=>'']);
		Dependence::create(["code"=>'0301', "dependence"=>'VICE-RECTORADO ACADEMICO', "ubication"=>'']);
		Dependence::create(["code"=>'0302', "dependence"=>'VICE-RECTORADO ADMINISTRATIVO', "ubication"=>'']);
		Dependence::create(["code"=>'0303', "dependence"=>'DIRECCION DE PREVENCION SEGURIDAD Y VIGILANCIA', "ubication"=>'']);
		Dependence::create(["code"=>'0304', "dependence"=>'DIRECCION DE BIBLIOTECA CENTRAL', "ubication"=>'']);
		Dependence::create(["code"=>'0305', "dependence"=>'ORDENACION DE PAGO', "ubication"=>'']);
		Dependence::create(["code"=>'0306', "dependence"=>'AGROUNERG', "ubication"=>'']);
		Dependence::create(["code"=>'0307', "dependence"=>'DEPARTAMENTO DE ARCHIVO GENERAL', "ubication"=>'']);
		Dependence::create(["code"=>'0308', "dependence"=>'DIRECCION DE RELACIONES PUBLICAS', "ubication"=>'']);
		Dependence::create(["code"=>'0310', "dependence"=>'DEPARTAMENTO DE CLINICAS MEDICAS', "ubication"=>'']);
		Dependence::create(["code"=>'0311', "dependence"=>'EQUIPOS DE HERRAMIENTAS Y TALLER SERGE', "ubication"=>'']);
		Dependence::create(["code"=>'0312', "dependence"=>'OFICINA DE EDUCACION MEDICA', "ubication"=>'']);
		Dependence::create(["code"=>'0313', "dependence"=>'IDESSA', "ubication"=>'']);
		Dependence::create(["code"=>'0314', "dependence"=>'DIRECCION DEL PROGRAMA DE MEDICINA', "ubication"=>'']);
		Dependence::create(["code"=>'0315', "dependence"=>'OFICINA DE APOYO DOCENTE', "ubication"=>'']);
		Dependence::create(["code"=>'0316', "dependence"=>'OFICINA SECT DE CONTROL DE ESTUDIOS CS SALUD', "ubication"=>'']);
		Dependence::create(["code"=>'0317', "dependence"=>'CUBICULOS PROFESORES AREA DE SALUD', "ubication"=>'']);
		Dependence::create(["code"=>'0318', "dependence"=>'DEPARTAMENTO DE SALUD PUBLICA', "ubication"=>'']);
		Dependence::create(["code"=>'0319', "dependence"=>'DEPARTAMENTO DE SALUD MENTAL', "ubication"=>'']);
		Dependence::create(["code"=>'0320', "dependence"=>'DEPARTAMENTO DE SALUD COMUNITARIA', "ubication"=>'']);
		Dependence::create(["code"=>'0401', "dependence"=>'ATENCION ESTUDIANTIL', "ubication"=>'']);
		Dependence::create(["code"=>'0402', "dependence"=>'LABORATORIO DE COMPUTACION DE INGENIERIA', "ubication"=>'']);
		Dependence::create(["code"=>'0403', "dependence"=>'DIRECCION DE INFORMATICA', "ubication"=>'']);
		Dependence::create(["code"=>'0404', "dependence"=>'DECANATO DE INFORMATICA', "ubication"=>'']);
		Dependence::create(["code"=>'0405', "dependence"=>'COORDINACION SECTORIAL DE ATENCION ESTUDIANTIL', "ubication"=>'']);
		Dependence::create(["code"=>'0406', "dependence"=>'DECANATO DE INGENIERIA DE SISTEMAS', "ubication"=>'']);
		Dependence::create(["code"=>'0501', "dependence"=>'AULA DE TOPOGRAFIA', "ubication"=>'']);
		Dependence::create(["code"=>'0502', "dependence"=>'DECANATO DEL AREA DE INGENIERIA', "ubication"=>'']);
		Dependence::create(["code"=>'0503', "dependence"=>'DECANATO DEL AREA DE CS DE LA SALUD', "ubication"=>'']);
		Dependence::create(["code"=>'0505', "dependence"=>'DECANATO DEL AREA DE CS DE LA SALUD AULA 1', "ubication"=>'']);
		Dependence::create(["code"=>'0506', "dependence"=>'AULA 02 AREA CS DE LA SALUD', "ubication"=>'']);
		Dependence::create(["code"=>'0507', "dependence"=>'AULA 03 AREA CS DE LA SALUD', "ubication"=>'']);
		Dependence::create(["code"=>'0508', "dependence"=>'AULA 04 AREA CS DE LA SALUD', "ubication"=>'']);
		Dependence::create(["code"=>'0509', "dependence"=>'AULA 05 AREA CS DE LA SALUD', "ubication"=>'']);
		Dependence::create(["code"=>'0510', "dependence"=>'AULA 06 AREA CS DE LA SALUD', "ubication"=>'']);
		Dependence::create(["code"=>'0511', "dependence"=>'AULA 07 AREA CS DE LA SALUD', "ubication"=>'']);
		Dependence::create(["code"=>'0512', "dependence"=>'AULA 08 AREA CS DE LA SALUD', "ubication"=>'']);
		Dependence::create(["code"=>'0513', "dependence"=>'DEPARTAMENTO SOCIALES E INVESTIGACION', "ubication"=>'']);
		Dependence::create(["code"=>'0514', "dependence"=>'SALON DE PROFESORES AREA DE ODONTOLOGIA', "ubication"=>'']);
		Dependence::create(["code"=>'0515', "dependence"=>'DEPARTAMENTO DE CS FUNCIONALES', "ubication"=>'']);
		Dependence::create(["code"=>'0516', "dependence"=>'CUBICULO DE PROFESORES ENFERMERIA', "ubication"=>'']);
		Dependence::create(["code"=>'0517', "dependence"=>'ESTACION PISCICOLA', "ubication"=>'']);
		Dependence::create(["code"=>'0518', "dependence"=>'CENTRO DE ESTUDIOS SOCIALES CENSA', "ubication"=>'']);
		Dependence::create(["code"=>'0520', "dependence"=>'DEPARTAMENTO DE REPRODUCCION GRAFICA (DEC DE INVEST)', "ubication"=>'']);
		Dependence::create(["code"=>'0601', "dependence"=>'AREA DE CS DE LA EDUCACION (CALABOZO)', "ubication"=>'']);
		Dependence::create(["code"=>'0602', "dependence"=>'DEPARTAMENTO DE CS MORFOLOGICAS', "ubication"=>'']);
		Dependence::create(["code"=>'0603', "dependence"=>'DEPARTAMENTO DE CLINICAS DE ENFERMERIAS', "ubication"=>'']);
		Dependence::create(["code"=>'0604', "dependence"=>'CENTRO JARDIN BOTANICO', "ubication"=>'']);
		Dependence::create(["code"=>'0605', "dependence"=>'CENTRO CLINICO UNIVERSITARIO', "ubication"=>'']);
		Dependence::create(["code"=>'0606', "dependence"=>'LABORATORIO CENTRAL AREA ACADEMICA', "ubication"=>'']);
		Dependence::create(["code"=>'0607', "dependence"=>'DIRECCION DEL PROGRAMA PRODUCCION VEGETAL', "ubication"=>'']);
		Dependence::create(["code"=>'0608', "dependence"=>'DIRECCION DEL PROGRAMA PRODCCION ANIMAL', "ubication"=>'']);
		Dependence::create(["code"=>'0609', "dependence"=>'DIRECCION DEL PROGRAMA DE ENFERMERIA', "ubication"=>'']);
		Dependence::create(["code"=>'0610', "dependence"=>'DIRECCION DE RECURSOS HUMANOS', "ubication"=>'']);
		Dependence::create(["code"=>'0611', "dependence"=>'DIRECCION GENERAL DE ADMINISTRACION', "ubication"=>'']);
		Dependence::create(["code"=>'0620', "dependence"=>'DEPARTAMENTO DE CS SOCIALES Y ECONOMICAS', "ubication"=>'']);
		Dependence::create(["code"=>'0621', "dependence"=>'DEPARTAMENTO DE CS SOCIALES Y ECONOMICASCUBICULO 2', "ubication"=>'']);
		Dependence::create(["code"=>'0622', "dependence"=>'DEPARTAMENTO DE CS SOCIALES Y ECONOMICASCUBICULO 7', "ubication"=>'']);
		Dependence::create(["code"=>'0623', "dependence"=>'DEPARTAMENTO DE CS SOCIALES Y ECONOMICASCUBICULO 8', "ubication"=>'']);
		Dependence::create(["code"=>'0624', "dependence"=>'DEPARTAMENTO DE CS SOCIALES Y ECONOMICASCUBICULO 9', "ubication"=>'']);
		Dependence::create(["code"=>'0625', "dependence"=>'DEPARTAMENTO DE CS SOCIALES Y ECONOMICASCUBICULO 10', "ubication"=>'']);
		Dependence::create(["code"=>'0626', "dependence"=>'DEPARTAMENTO DE CS SOCIALES Y ECONOMICASCUBICULO 11', "ubication"=>'']);
		Dependence::create(["code"=>'0627', "dependence"=>'DEPARTAMENTO DE CS SOCIALES Y ECONOMICASCUBICULO 13', "ubication"=>'']);
		Dependence::create(["code"=>'0628', "dependence"=>'DEPARTAMENTO DE CS SOCIALES Y ECONOMICASCUBICULO 14', "ubication"=>'']);
		Dependence::create(["code"=>'0629', "dependence"=>'DEPARTAMENTO DE CS SOCIALES Y ECONOMICASCUBICULO 18', "ubication"=>'']);
		Dependence::create(["code"=>'0630', "dependence"=>'DEPARTAMENTO DE INGENIERIA', "ubication"=>'']);
		Dependence::create(["code"=>'0631', "dependence"=>'DEPARTAMENTO DE INGENIERIA CUBICULO 12', "ubication"=>'']);
		Dependence::create(["code"=>'0632', "dependence"=>'DEPARTAMENTO DE INGENIERIA CUBICULO 22', "ubication"=>'']);
		Dependence::create(["code"=>'0633', "dependence"=>'DEPARTAMENTO DE INGENIERIA CUBICULO 25', "ubication"=>'']);
		Dependence::create(["code"=>'0634', "dependence"=>'DEPARTAMENTO DE INGENIERIA CUBICULO 36', "ubication"=>'']);
		Dependence::create(["code"=>'0635', "dependence"=>'DEPARTAMENTO DE INGENIERIA CUBICULO 39', "ubication"=>'']);
		Dependence::create(["code"=>'0636', "dependence"=>'DEPARTAMENTO DE INGENIERIA CUBICULO 45', "ubication"=>'']);
		Dependence::create(["code"=>'0637', "dependence"=>'DEPARTAMENTO DE INGENIERIA CUBICULO 46', "ubication"=>'']);
		Dependence::create(["code"=>'0638', "dependence"=>'DEPARTAMENTO DE CS SOCIALES Y ECONOMICAS CUBICULO 33', "ubication"=>'']);
		Dependence::create(["code"=>'0639', "dependence"=>'DEPARTAMENTO DE CS SOCIALES Y ECONOMICAS CUBICULO 41', "ubication"=>'']);
		Dependence::create(["code"=>'0640', "dependence"=>'DIRECCION DEL PROGRAMA DE ESTUDIOS COMUNES', "ubication"=>'']);
		Dependence::create(["code"=>'0641', "dependence"=>'CUBICULO 5 ', "ubication"=>'']);
		Dependence::create(["code"=>'0642', "dependence"=>'CUBICULO 16', "ubication"=>'']);
		Dependence::create(["code"=>'0643', "dependence"=>'CUBICULO 19', "ubication"=>'']);
		Dependence::create(["code"=>'0644', "dependence"=>'CUBICULO 34', "ubication"=>'']);
		Dependence::create(["code"=>'0645', "dependence"=>'CUBICULO 38', "ubication"=>'']);
		Dependence::create(["code"=>'0646', "dependence"=>'CUBICULO 40', "ubication"=>'']);
		Dependence::create(["code"=>'0647', "dependence"=>'CUBICULO 42', "ubication"=>'']);
		Dependence::create(["code"=>'0648', "dependence"=>'CUBICULO 43', "ubication"=>'']);
		Dependence::create(["code"=>'0649', "dependence"=>'CUBICULO 44', "ubication"=>'']);
		Dependence::create(["code"=>'0650', "dependence"=>'CUBICULO 47', "ubication"=>'']);
		Dependence::create(["code"=>'0651', "dependence"=>'CUBICULO 50', "ubication"=>'']);
		Dependence::create(["code"=>'0652', "dependence"=>'CUBICULO DE EDAFOLOGIA', "ubication"=>'']);
		Dependence::create(["code"=>'0670', "dependence"=>'DEPARTAMENTO DE ASIGNATURAS INSTRUMENTALES', "ubication"=>'']);
		Dependence::create(["code"=>'0671', "dependence"=>'DEPARTAMENTO DE ASIGNATURAS INSTRUMENTALES CUBICULO 1', "ubication"=>'']);
		Dependence::create(["code"=>'0672', "dependence"=>'DEPARTAMENTO DE ASIGNATURAS INSTRUMENTALES CUBICULO 3', "ubication"=>'']);
		Dependence::create(["code"=>'0673', "dependence"=>'DEPARTAMENTO DE ASIGNATURAS INSTRUMENTALES CUBICULO 15', "ubication"=>'']);
		Dependence::create(["code"=>'0674', "dependence"=>'DEPARTAMENTO DE ASIGNATURAS INSTRUMENTALES CUBICULO 21', "ubication"=>'']);
		Dependence::create(["code"=>'0675', "dependence"=>'DEPARTAMENTO DE ASIGNATURAS INSTRUMENTALES CUBICULO 27', "ubication"=>'']);
		Dependence::create(["code"=>'0676', "dependence"=>'DEPARTAMENTO DE ASIGNATURAS INSTRUMENTALES CUBICULO 28', "ubication"=>'']);
		Dependence::create(["code"=>'0677', "dependence"=>'DEPARTAMENTO DE ASIGNATURAS INSTRUMENTALES CUBICULO 30', "ubication"=>'']);
		Dependence::create(["code"=>'0678', "dependence"=>'DEPARTAMENTO DE ASIGNATURAS INSTRUMENTALES CUBICULO31', "ubication"=>'']);
		Dependence::create(["code"=>'0679', "dependence"=>'DEPARTAMENTO DE ASIGNATURAS INSTRUMENTALES CUBICULO 32', "ubication"=>'']);
		Dependence::create(["code"=>'0680', "dependence"=>'DEPARTAMENTO DE ASIGNATURAS INSTRUMENTALES CUBICULO 35', "ubication"=>'']);
		Dependence::create(["code"=>'0681', "dependence"=>'DEPARTAMENTO DE ASIGNATURAS INSTRUMENTALES CUBICULO 48', "ubication"=>'']);
		Dependence::create(["code"=>'0691', "dependence"=>'DEPARTAMENTO DE CLINICAS CUBICULO 1', "ubication"=>'']);
		Dependence::create(["code"=>'0692', "dependence"=>'DEPARTAMENTO DE CLINICAS CUBICULO 2', "ubication"=>'']);
		Dependence::create(["code"=>'0693', "dependence"=>'DEPARTAMENTO DE CLINICAS CUBICULO 3', "ubication"=>'']);
		Dependence::create(["code"=>'0694', "dependence"=>'DEPARTAMENTO DE CLINICAS CUBICULO 4', "ubication"=>'']);
		Dependence::create(["code"=>'0701', "dependence"=>'DIRECCION DE CONTABILIDAD', "ubication"=>'']);
		Dependence::create(["code"=>'0702', "dependence"=>'DIRECCION DE PRESUPUESTO', "ubication"=>'']);
		Dependence::create(["code"=>'0703', "dependence"=>'DIRECCION DE COMPRAS', "ubication"=>'']);
		Dependence::create(["code"=>'0704', "dependence"=>'DIRECCION DE FINANZAS', "ubication"=>'']);
		Dependence::create(["code"=>'0705', "dependence"=>'DIRECCION DE SERVICIOS GENERALES', "ubication"=>'']);
		Dependence::create(["code"=>'0801', "dependence"=>'CENTRO DE ESTUDIANTES DE MEDICINA', "ubication"=>'']);
		Dependence::create(["code"=>'0802', "dependence"=>'CENTRO DE PRODUCCION DE OVINOS Y CAPRINOS', "ubication"=>'']);
		Dependence::create(["code"=>'0803', "dependence"=>'DIRECCION DE DEPORTES', "ubication"=>'']);
		Dependence::create(["code"=>'0804', "dependence"=>'ASOFAUNA', "ubication"=>'']);
		Dependence::create(["code"=>'0805', "dependence"=>'DIRECCION DE CONTROL Y EVALUACION DE ESTUDIOS', "ubication"=>'']);
		Dependence::create(["code"=>'0807', "dependence"=>'COORDINACION DE CONTROL DE ESTUDIOS', "ubication"=>'']);
		Dependence::create(["code"=>'0808', "dependence"=>'AULA 06 AREA DE INGENIERIA', "ubication"=>'']);
		Dependence::create(["code"=>'0809', "dependence"=>'COORDINACION DE SEGUROS', "ubication"=>'']);
		Dependence::create(["code"=>'0810', "dependence"=>'SECCION DE BIENES', "ubication"=>'']);
		Dependence::create(["code"=>'0811', "dependence"=>'DIRECCION DE TRASNPORTE', "ubication"=>'']);
		Dependence::create(["code"=>'0812', "dependence"=>'DEPARTAMENTO DE AGRONOMIA', "ubication"=>'']);
		Dependence::create(["code"=>'0813', "dependence"=>'COORDINACION DE TUTORIAS', "ubication"=>'']);
		Dependence::create(["code"=>'0814', "dependence"=>'CONSEJO DE AREA DE INGENIERIA', "ubication"=>'']);
		Dependence::create(["code"=>'0815', "dependence"=>'ALMACEN', "ubication"=>'']);
		Dependence::create(["code"=>'0816', "dependence"=>'DECANATO DE CS ECONOMICAS', "ubication"=>'']);
		Dependence::create(["code"=>'0817', "dependence"=>'DEPARTAMENTO DE CS ANIMAL', "ubication"=>'']);
		Dependence::create(["code"=>'0818', "dependence"=>'SECCION DE CAJA', "ubication"=>'']);
		Dependence::create(["code"=>'0819', "dependence"=>'ESTACION APICOLA', "ubication"=>'']);
		Dependence::create(["code"=>'0822', "dependence"=>'MAQUINARIAS Y EQUIPOS AGRICOLAS Y PECUARIOS', "ubication"=>'']);
		Dependence::create(["code"=>'0823', "dependence"=>'EQUIPO DE TRANSPORTE', "ubication"=>'']);
		Dependence::create(["code"=>'0824', "dependence"=>'COMEDOR UNIVERSITARIO', "ubication"=>'']);
		Dependence::create(["code"=>'0825', "dependence"=>'CENTRO DE ESTUDIANTES AREA DE INGENIERIA', "ubication"=>'']);
		Dependence::create(["code"=>'0826', "dependence"=>'SOUNERG', "ubication"=>'']);
		Dependence::create(["code"=>'0901', "dependence"=>'DEPARTAMENTO DE PRODUCCION ANIMAL', "ubication"=>'']);
		Dependence::create(["code"=>'0902', "dependence"=>'AETAS UNERG', "ubication"=>'']);
		Dependence::create(["code"=>'0903', "dependence"=>'CENTRO DE INVEST. Y EXTEN EN AGUA Y SUELOS (CIESA)', "ubication"=>'']);
		Dependence::create(["code"=>'0904', "dependence"=>'LABORATORIO (ZARAZA)', "ubication"=>'']);
		Dependence::create(["code"=>'0905', "dependence"=>'AREA DE ESTUDIOS CONTINUOS', "ubication"=>'']);
		Dependence::create(["code"=>'0906', "dependence"=>'AREA DE INGENIERIA', "ubication"=>'']);
		Dependence::create(["code"=>'0907', "dependence"=>'OFICINA DE ADMINISTRACION (ZARAZA)', "ubication"=>'']);
		Dependence::create(["code"=>'0908', "dependence"=>'CONTROL DE ESTUDIOS (ZARAZA)', "ubication"=>'']);
		Dependence::create(["code"=>'0909', "dependence"=>'DECANATO DE MEDICINA VETERINARIA', "ubication"=>'']);
		Dependence::create(["code"=>'0910', "dependence"=>'AULA UNERG AREA DE MEDICINA', "ubication"=>'']);
		Dependence::create(["code"=>'0911', "dependence"=>'UNIDAD DE ATENCION ESTUDIANTIL', "ubication"=>'']);
		Dependence::create(["code"=>'0915', "dependence"=>'BIBLIOTECA (ZARAZA)', "ubication"=>'']);
		Dependence::create(["code"=>'0916', "dependence"=>'FEDERACION DE CENTROS UNIVERSITARIOS', "ubication"=>'']);
		Dependence::create(["code"=>'0917', "dependence"=>'CENTRO DOCENTE DE PRODUCCION E INVESTIGACION AVICOLA', "ubication"=>'']);
		Dependence::create(["code"=>'0918', "dependence"=>'SALA DE COMPUTACION', "ubication"=>'']);
		Dependence::create(["code"=>'0919', "dependence"=>'QUIROFANO (ZARAZA)', "ubication"=>'']);
		Dependence::create(["code"=>'0920', "dependence"=>'SALON DE PROFESORES (ZARAZA)', "ubication"=>'']);
		Dependence::create(["code"=>'0413', "dependence"=>'AREA DE CS ECONOMICAS (V. DE LA PASCUA)', "ubication"=>'']);
		Dependence::create(["code"=>'0415', "dependence"=>'AREA DE SALUD (V. DE LA PASCUA)', "ubication"=>'']);
    }
}
